# config/mongomapper.yml

options: &options
  parameterize_keys: false

defaults: &defaults
  host: localhost
  adapter: mongodb
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  <<: *options
  database: jp2_development

test:
  <<: *defaults
  <<: *options
  database: pf_testing

production:
  uri: mongodb://chedigitz:welcome11@flame.mongohq.com:27103/pf_test
