# config/mongoid.yml

options: &options
  parameterize_keys: false

defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  <<: *options
  database: jp2

test:
  <<: *defaults
  <<: *options
  database: pf2_test

production:
  <<: *options
  uri: flame.mongohq.com
  database: pf_test
  username: chedigitz
  password: welcome11
  port: 27103